// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/2/2025, 3:36:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/plugins/**/*.{js,ts,mjs}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/composables/**/*.{js,ts,mjs}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/utils/**/*.{js,ts,mjs}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rimshaafzal/Documents/GitHub/varnish-dashboard-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;